package database

import (
	"fmt"
	"log"
	"math/rand"
	"strings"
	"time"

	"gocommerce-backend/internal/domain/auth"
	"gocommerce-backend/internal/domain/order"
	"gocommerce-backend/internal/domain/product"
	"gocommerce-backend/internal/utils"
	"gorm.io/gorm"
)

type productTemplate struct {
	Name        string
	CategoryIdx int
	SKUPrefix   string
	Description string
	Price       float64
	Stock       int
	LowStock    int
	ImageURL    string
	Badge       string
	Rating      float64
}

func Seed(db *gorm.DB) error {
	var userCount int64
	db.Model(&auth.User{}).Count(&userCount)
	if userCount > 0 {
		return nil // Already seeded
	}

	log.Println("Memulai proses seeding 100 produk retail Tirenn Commerce (Bahasa Indonesia)...")

	// 1. Seed Pengguna (Users)
	adminPassword, _ := utils.HashPassword("Admin@123")
	customerPassword, _ := utils.HashPassword("Shopper@123")
	sarahPassword, _ := utils.HashPassword("Sarah@123")

	admin := auth.User{
		Name:         "Tirenn Merchant Admin",
		Email:        "admin@gocommerce.com",
		PasswordHash: adminPassword,
		Role:         auth.RoleAdmin,
		Phone:        "+62 811-9876-5432",
		Address:      "Gedung Menara Sudirman Lt. 18, Jl. Jend. Sudirman Kav. 60, Jakarta Selatan",
		Status:       auth.StatusActive,
	}
	db.Create(&admin)

	shopper := auth.User{
		Name:         "Budi Santoso",
		Email:        "shopper@gocommerce.com",
		PasswordHash: customerPassword,
		Role:         auth.RoleCustomer,
		Phone:        "+62 812-3456-7890",
		Address:      "Jl. Menteng Raya No. 24, RT 02/RW 05, Jakarta Pusat",
		Status:       auth.StatusActive,
	}
	db.Create(&shopper)

	sarah := auth.User{
		Name:         "Siti Rahmawati",
		Email:        "sarah.jenkins@example.com",
		PasswordHash: sarahPassword,
		Role:         auth.RoleCustomer,
		Phone:        "+62 813-7890-1234",
		Address:      "Jl. Dago Asri No. 12, Coblong, Bandung, Jawa Barat",
		Status:       auth.StatusActive,
	}
	db.Create(&sarah)

	// 2. Seed 8 Kategori Toko Retail (Categories)
	categories := []product.Category{
		{
			Name:        "Elektronik & Gadget",
			Slug:        "elektronik-gadget",
			Description: "Headphone nirkabel, smartwatch kesehatan, keyboard mekanikal, dan aksesoris teknologi terkini.",
			Icon:        "⚡",
		},
		{
			Name:        "Fashion Pria",
			Slug:        "fashion-pria",
			Description: "Pakaian kasual pria, kemeja formal, jaket streetwear, dan sepatu kulit pria berkualitas.",
			Icon:        "👔",
		},
		{
			Name:        "Fashion Wanita",
			Slug:        "fashion-wanita",
			Description: "Blouse modis, gaun wanita, tas bahu elegan, dan pakaian kasual wanita terkini.",
			Icon:        "👗",
		},
		{
			Name:        "Peralatan Rumah Tangga",
			Slug:        "peralatan-rumah-tangga",
			Description: "Perlengkapan dapur modern, penggiling kopi barista, lampu ambient cerdas, dan perabot rumah.",
			Icon:        "🏡",
		},
		{
			Name:        "Olahraga & Outdoor",
			Slug:        "olahraga-outdoor",
			Description: "Peralatan gym, tas gunung waterproof, botol tumbler vacuum, dan perlengkapan lari.",
			Icon:        "🎒",
		},
		{
			Name:        "Kecantikan & Perawatan",
			Slug:        "kecantikan-perawatan",
			Description: "Serum pencerah kulit herbal, tabir surya SPF 50+, dan produk perawatan kulit wajah alami.",
			Icon:        "✨",
		},
		{
			Name:        "Makanan & Minuman Sehat",
			Slug:        "makanan-minuman-sehat",
			Description: "Biji kopi single-origin Nusantara, madu hutan murni, teh herbal, dan camilan organik bernutrisi.",
			Icon:        "☕",
		},
		{
			Name:        "Buku & Alat Tulis",
			Slug:        "buku-alat-tulis",
			Description: "Buku catatan kulit premium, pulpen kaligrafi ergonomis, dan perlengkapan meja kerja produktif.",
			Icon:        "📚",
		},
	}
	for i := range categories {
		db.Create(&categories[i])
	}

	// 3. Seed 100 Produk Retail Bahasa Indonesia
	catalog := []productTemplate{
		// === 1. ELEKTRONIK & GADGET (15 Produk) ===
		{
			Name:        "Headphone Nirkabel AuraPro ANC Premium",
			CategoryIdx: 0,
			SKUPrefix:   "ELEC",
			Description: "Headphone over-ear nirkabel dengan teknologi peredam bising aktif (Active Noise Cancellation), driver titanium 40mm bertenaga, daya tahan baterai hingga 45 jam, dan bantalan telinga memory foam empuk.",
			Price:       1499000,
			Stock:       35,
			LowStock:    8,
			ImageURL:    "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
			Badge:       "TERLARIS",
			Rating:      4.9,
		},
		{
			Name:        "Smartwatch TitanFit Ultra Layar AMOLED",
			CategoryIdx: 0,
			SKUPrefix:   "ELEC",
			Description: "Layar AMOLED safir jernih, sensor pemantau kadar oksigen darah (SpO2) dan detak jantung real-time, tahan air 5ATM, GPS bawaan, serta sinkronisasi otomatis ke Android dan iOS.",
			Price:       899000,
			Stock:       25,
			LowStock:    5,
			ImageURL:    "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80",
			Badge:       "TOP RATED",
			Rating:      4.8,
		},
		{
			Name:        "Keyboard Mekanikal Wireless ApexCraft RGB 75%",
			CategoryIdx: 0,
			SKUPrefix:   "ELEC",
			Description: "Keyboard mekanikal kompak 75% hot-swappable dengan switch linear halus berpelumas, bodi aluminium CNC kokoh, keycaps PBT tahan aus, dan konektivitas 3 mode (2.4GHz / Bluetooth / USB-C).",
			Price:       1199000,
			Stock:       18,
			LowStock:    4,
			ImageURL:    "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80",
			Badge:       "PROMO",
			Rating:      4.9,
		},
		{
			Name:        "Earbuds TWS BassBoom SoundCore Nirkabel",
			CategoryIdx: 0,
			SKUPrefix:   "ELEC",
			Description: "Earphone nirkabel true wireless dengan dynamic bass 13mm, latensi rendah 40ms untuk gaming, mikrofon ganda berteknologi ENC untuk panggilan telepon jernih, dan case wireless charging.",
			Price:       349000,
			Stock:       50,
			LowStock:    10,
			ImageURL:    "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80",
			Badge:       "POPULER",
			Rating:      4.7,
		},
		{
			Name:        "Powerbank Fast Charging 20000mAh 65W GaN",
			CategoryIdx: 0,
			SKUPrefix:   "ELEC",
			Description: "Powerbank bertenaga besar 20000mAh dengan port USB-C Power Delivery 65W, sanggup mengisi daya laptop ultrabook, tablet, dan smartphone secara bersamaan.",
			Price:       459000,
			Stock:       40,
			LowStock:    8,
			ImageURL:    "https://images.unsplash.com/photo-1609592426860-23d9b0485906?w=600&auto=format&fit=crop&q=80",
			Badge:       "ESSENTIAL",
			Rating:      4.8,
		},
		{
			Name:        "Mouse Gaming Nirkabel Ultra-Lightweight 58g",
			CategoryIdx: 0,
			SKUPrefix:   "ELEC",
			Description: "Mouse gaming nirkabel berbobot super ringan 58 gram dengan sensor optik 26000 DPI, switch optik tahan 90 juta klik, dan kabel paracord fleksibel.",
			Price:       599000,
			Stock:       30,
			LowStock:    6,
			ImageURL:    "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80",
			Badge:       "GAMING",
			Rating:      4.9,
		},
		{
			Name:        "Speaker Bluetooth Portabel Outdoor Waterproof IPX7",
			CategoryIdx: 0,
			SKUPrefix:   "ELEC",
			Description: "Speaker portabel tahan air IPX7 dengan suara surround 360 derajat, dual passive radiator bass bertenaga, dan baterai tahan hingga 16 jam non-stop.",
			Price:       399000,
			Stock:       32,
			LowStock:    7,
			ImageURL:    "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop&q=80",
			Badge:       "OUTDOOR",
			Rating:      4.8,
		},
		{
			Name:        "Webcam 4K Ultra HD Autofocus Mikrofon Stereo",
			CategoryIdx: 0,
			SKUPrefix:   "ELEC",
			Description: "Kamera webcam resolusi 4K dengan sensor Sony CMOS, koreksi pencahayaan otomatis saat redup, tutup privasi fisik, dan penyangga tripod fleksibel.",
			Price:       749000,
			Stock:       15,
			LowStock:    4,
			ImageURL:    "https://images.unsplash.com/photo-1588702547923-7093a6c3ba33?w=600&auto=format&fit=crop&q=80",
			Badge:       "OFFICE",
			Rating:      4.7,
		},
		{
			Name:        "Charger Dinding GaN 100W 4-Port Fast Charge",
			CategoryIdx: 0,
			SKUPrefix:   "ELEC",
			Description: "Adaptor charger teknologi GaN III ringkas dengan 3 port USB-C dan 1 port USB-A, mendukung protokol PD 3.0, QC 4+, dan proteksi overheat cerdas.",
			Price:       329000,
			Stock:       45,
			LowStock:    10,
			ImageURL:    "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80",
			Badge:       "FAST CHARGE",
			Rating:      4.9,
		},
		{
			Name:        "Mikrofon Kondensor USB Studio Podcast & Streaming",
			CategoryIdx: 0,
			SKUPrefix:   "ELEC",
			Description: "Mikrofon USB plug-and-play pola pickup cardioid dengan filter pop bawaan, tombol sentuh mute instan, dan jack monitor headphone zero-latency 3.5mm.",
			Price:       689000,
			Stock:       20,
			LowStock:    5,
			ImageURL:    "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&auto=format&fit=crop&q=80",
			Badge:       "STREAMER",
			Rating:      4.8,
		},
		{
			Name:        "Lampu Monitor Bar ScreenBar Auto-Dimming",
			CategoryIdx: 0,
			SKUPrefix:   "ELEC",
			Description: "Lampu gantung monitor komputer dengan pencahayaan asimetris anti-silau di layar, pengatur suhu warna sentuh nirkabel, dan sensor cahaya ruangan otomatis.",
			Price:       379000,
			Stock:       28,
			LowStock:    6,
			ImageURL:    "https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=600&auto=format&fit=crop&q=80",
			Badge:       "DESK SETUP",
			Rating:      4.7,
		},
		{
			Name:        "Hub USB-C 8-in-1 HDMI 4K Gigabit Ethernet",
			CategoryIdx: 0,
			SKUPrefix:   "ELEC",
			Description: "Docking dongle multiport aluminium dengan output HDMI 4K 60Hz, slot kartu SD/TF kecepatan tinggi, LAN Gigabit RJ45, dan pengisian daya 100W PD Pass-through.",
			Price:       299000,
			Stock:       38,
			LowStock:    8,
			ImageURL:    "https://images.unsplash.com/photo-1544652478-6653e09f18a2?w=600&auto=format&fit=crop&q=80",
			Badge:       "BEST DEAL",
			Rating:      4.8,
		},
		{
			Name:        "Stylus Pen Universal Palm Rejection Presisi Tinggi",
			CategoryIdx: 0,
			SKUPrefix:   "ELEC",
			Description: "Pena digital kapasitif dengan sensor kemiringan (tilt sensitivity), pengisian daya nirkabel magnetik, ujung pena POM halus anti-gores layar tablet.",
			Price:       259000,
			Stock:       34,
			LowStock:    7,
			ImageURL:    "https://images.unsplash.com/photo-1585336261026-7f576e2820d8?w=600&auto=format&fit=crop&q=80",
			Badge:       "CREATIVE",
			Rating:      4.7,
		},
		{
			Name:        "Gamepad Controller Wireless Bluetooth Hall Effect",
			CategoryIdx: 0,
			SKUPrefix:   "ELEC",
			Description: "Stick kontroler gaming dengan joystick dan trigger sensor magnetik Hall Effect anti-drifting, getaran haptic ganda, kompatibel PC, Switch, Android & iOS.",
			Price:       429000,
			Stock:       22,
			LowStock:    5,
			ImageURL:    "https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=600&auto=format&fit=crop&q=80",
			Badge:       "GAMING",
			Rating:      4.8,
		},
		{
			Name:        "Kabel Data USB-C to USB-C 240W Nylon Braided 2M",
			CategoryIdx: 0,
			SKUPrefix:   "ELEC",
			Description: "Kabel pengisian daya cepat 240W E-Marker chip dengan rajutan nilon balistik tebal anti-kusut dan transfer data kecepatan tinggi 480Mbps.",
			Price:       89000,
			Stock:       80,
			LowStock:    15,
			ImageURL:    "https://images.unsplash.com/photo-1541689592655-f5f52825a3b8?w=600&auto=format&fit=crop&q=80",
			Badge:       "MURAH",
			Rating:      4.9,
		},

		// === 2. FASHION PRIA (13 Produk) ===
		{
			Name:        "Hoodie Heavyweight Cotton UrbanCraft Streetwear",
			CategoryIdx: 1,
			SKUPrefix:   "FASH-M",
			Description: "Hoodie katun organik 420 GSM tebal dan lembut, potongan oversized modern, tudung ganda berlapis, karet manset ribbed elastis, dan jahitan presisi standar streetwear.",
			Price:       389000,
			Stock:       45,
			LowStock:    10,
			ImageURL:    "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80",
			Badge:       "TERLARIS",
			Rating:      4.8,
		},
		{
			Name:        "Jaket Windbreaker Commuter AeroFlex Waterproof",
			CategoryIdx: 1,
			SKUPrefix:   "FASH-M",
			Description: "Jaket tahan angin dan air berbahan ripstop ultra-ringan, ritsleting kedap air YKK AquaGuard, lubang ventilasi ketiak yang sejuk, dan tudung praktis yang bisa dilipat.",
			Price:       549000,
			Stock:       22,
			LowStock:    6,
			ImageURL:    "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&auto=format&fit=crop&q=80",
			Badge:       "TRENDING",
			Rating:      4.8,
		},
		{
			Name:        "Kaos Polos Oversized Katun Combed 24s Heavy",
			CategoryIdx: 1,
			SKUPrefix:   "FASH-M",
			Description: "Kaos katun combed 24s premium adem dan menyerap keringat, potongan rileks tidak mudah melar, kerah rib 3cm kokoh, cocok untuk gaya kasual sehari-hari.",
			Price:       129000,
			Stock:       70,
			LowStock:    15,
			ImageURL:    "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80",
			Badge:       "FAVORIT",
			Rating:      4.9,
		},
		{
			Name:        "Kemeja Flanel Lengan Panjang Kotak Klasik",
			CategoryIdx: 1,
			SKUPrefix:   "FASH-M",
			Description: "Kemeja flanel katun brushed wol halus yang hangat dan nyaman, pola kotak tartan timeless dengan saku depan fungsional dan kancing resin kokoh.",
			Price:       249000,
			Stock:       35,
			LowStock:    8,
			ImageURL:    "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&auto=format&fit=crop&q=80",
			Badge:       "KLASIK",
			Rating:      4.7,
		},
		{
			Name:        "Celana Jeans Pria Slim Fit Denim Stretch Washed",
			CategoryIdx: 1,
			SKUPrefix:   "FASH-M",
			Description: "Celana jeans denim stretch pria 13oz dengan potongan slim fit modern, aksen washed indigo elegan, saku dalam kuat, dan jahitan bar-tack tahan lama.",
			Price:       299000,
			Stock:       40,
			LowStock:    8,
			ImageURL:    "https://images.unsplash.com/photo-1542272604-780c96856592?w=600&auto=format&fit=crop&q=80",
			Badge:       "BEST SELLER",
			Rating:      4.9,
		},
		{
			Name:        "Sepatu Sneakers Canvas Low-Top Vulcanized",
			CategoryIdx: 1,
			SKUPrefix:   "FASH-M",
			Description: "Sneakers kanvas 12oz dengan sol karet vulkanisir anti-slip, insole busa memory empuk peredam benturan, dan jahitan tepi ganda yang kuat.",
			Price:       359000,
			Stock:       25,
			LowStock:    5,
			ImageURL:    "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80",
			Badge:       "SNEAKERS",
			Rating:      4.8,
		},
		{
			Name:        "Jaket Denim Trucker Vintage Indigo Washed",
			CategoryIdx: 1,
			SKUPrefix:   "FASH-M",
			Description: "Jaket jeans denim 14oz non-stretch dengan aksen wash vintage autentik, kancing kuningan kustom, dan empat kantong luar fungsional.",
			Price:       429000,
			Stock:       20,
			LowStock:    5,
			ImageURL:    "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&auto=format&fit=crop&q=80",
			Badge:       "VINTAGE",
			Rating:      4.9,
		},
		{
			Name:        "Dompet Kulit Asli Bifold Pull-Up Leather",
			CategoryIdx: 1,
			SKUPrefix:   "FASH-M",
			Description: "Dompet lipat dua berbahan kulit sapi asli jenis pull-up yang semakin mengkilap seiring waktu, dilengkapi 8 slot kartu dan proteksi RFID.",
			Price:       189000,
			Stock:       50,
			LowStock:    10,
			ImageURL:    "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop&q=80",
			Badge:       "KULIT ASLI",
			Rating:      4.9,
		},
		{
			Name:        "Celana Pendek Cargo Katun Ripstop Tactical",
			CategoryIdx: 1,
			SKUPrefix:   "FASH-M",
			Description: "Celana pendek santai berbahan ripstop anti-sobek dengan 6 kantong cargo serbaguna, pinggang karet elastis bertali, dan sirkulasi udara baik.",
			Price:       169000,
			Stock:       45,
			LowStock:    9,
			ImageURL:    "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600&auto=format&fit=crop&q=80",
			Badge:       "SANTAI",
			Rating:      4.7,
		},
		{
			Name:        "Topi Baseball Cap Katun Twill Unstructured",
			CategoryIdx: 1,
			SKUPrefix:   "FASH-M",
			Description: "Topi polo cap kasual katun washed lembut dengan strap pengatur gesper logam di belakang dan bordir logo minimalis di bagian depan.",
			Price:       89000,
			Stock:       60,
			LowStock:    12,
			ImageURL:    "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&auto=format&fit=crop&q=80",
			Badge:       "AKSESORIS",
			Rating:      4.8,
		},
		{
			Name:        "Kacamata Hitam Polarized Wayfarer UV400",
			CategoryIdx: 1,
			SKUPrefix:   "FASH-M",
			Description: "Kacamata gaya bingkai matte hitam dengan lensa polarized anti-silau UV400, engsel pegas lentur tahan patah, dan pouch pelindung microfiber.",
			Price:       149000,
			Stock:       40,
			LowStock:    8,
			ImageURL:    "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80",
			Badge:       "POLARIZED",
			Rating:      4.7,
		},
		{
			Name:        "Ikat Pinggang Kulit Reversible Gesper Otomatis",
			CategoryIdx: 1,
			SKUPrefix:   "FASH-M",
			Description: "Sabuk pria formal kulit sapi split 3.5cm dengan kepala gesper ratchet otomatis tanpa lubang yang presisi dan elegan.",
			Price:       139000,
			Stock:       35,
			LowStock:    7,
			ImageURL:    "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=600&auto=format&fit=crop&q=80",
			Badge:       "FORMAL",
			Rating:      4.8,
		},
		{
			Name:        "Sandal Slop Pria Ergonomis EVA Anti-Slip",
			CategoryIdx: 1,
			SKUPrefix:   "FASH-M",
			Description: "Sandal selop kasual berbahan busa EVA ringan dengan lekukan telapak kaki ergonomis, anti-air, cepat kering, dan tidak licin saat basah.",
			Price:       99000,
			Stock:       55,
			LowStock:    10,
			ImageURL:    "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=600&auto=format&fit=crop&q=80",
			Badge:       "HEMAT",
			Rating:      4.7,
		},

		// === 3. FASHION WANITA (12 Produk) ===
		{
			Name:        "Blouse Katun Linen Wanita Kerah V Elegan",
			CategoryIdx: 2,
			SKUPrefix:   "FASH-W",
			Description: "Blouse wanita katun linen alami bertekstur lembut dan sejuk di kulit, aksen kancing mutiara, lengan balon feminin, cocok untuk kantor maupun kasual.",
			Price:       189000,
			Stock:       35,
			LowStock:    7,
			ImageURL:    "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=600&auto=format&fit=crop&q=80",
			Badge:       "EFEKTIF KERJA",
			Rating:      4.8,
		},
		{
			Name:        "Celana Jeans Wanita High Waist Straight Leg Denim",
			CategoryIdx: 2,
			SKUPrefix:   "FASH-W",
			Description: "Celana jeans wanita model lurus straight leg dengan pinggang tinggi high waist, bahan denim katun premium non-stretch yang memberikan siluet kaki jenjang dan ramping.",
			Price:       269000,
			Stock:       40,
			LowStock:    8,
			ImageURL:    "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&auto=format&fit=crop&q=80",
			Badge:       "TRENDING JEANS",
			Rating:      4.9,
		},
		{
			Name:        "Cardigan Rajut Oversized Korean Style Knitwear",
			CategoryIdx: 2,
			SKUPrefix:   "FASH-W",
			Description: "Outer cardigan rajut benang katun akrilik tebal yang tidak gatal, kancing kayu bundar estetik, model dropped shoulder bergaya Korea santai.",
			Price:       229000,
			Stock:       30,
			LowStock:    6,
			ImageURL:    "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&auto=format&fit=crop&q=80",
			Badge:       "KOREAN LOOK",
			Rating:      4.8,
		},
		{
			Name:        "Dress Floral Midi A-Line Lengan Pendek",
			CategoryIdx: 2,
			SKUPrefix:   "FASH-W",
			Description: "Gaun midi motif bunga anggun berbahan rayon viscose jatuh dan adem, kerah vintage persegi dengan tali pita pinggang yang bisa disesuaikan.",
			Price:       259000,
			Stock:       25,
			LowStock:    5,
			ImageURL:    "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&auto=format&fit=crop&q=80",
			Badge:       "ANGGUN",
			Rating:      4.9,
		},
		{
			Name:        "Tas Totebag Kanvas Tebal dengan Resleting & Saku Laptop",
			CategoryIdx: 2,
			SKUPrefix:   "FASH-W",
			Description: "Tas totebag bahan kanvas katun tebal 14oz berpenutup resleting utama, saku dalam empuk untuk laptop 14 inci, dan tali bahu kuat.",
			Price:       149000,
			Stock:       60,
			LowStock:    12,
			ImageURL:    "https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80",
			Badge:       "KAMPUS & KERJA",
			Rating:      4.8,
		},
		{
			Name:        "Sepatu Flat Shoes Wanita Kulit Sintetis Busa Empuk",
			CategoryIdx: 2,
			SKUPrefix:   "FASH-W",
			Description: "Sepatu flat balet kulit sintetis lentur anti-lecet dengan sol karet fleksibel dan insole memory foam ekstra empuk untuk jalan seharian.",
			Price:       179000,
			Stock:       38,
			LowStock:    8,
			ImageURL:    "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&auto=format&fit=crop&q=80",
			Badge:       "ANTI LECET",
			Rating:      4.7,
		},
		{
			Name:        "Hijab Segi Empat Voal Premium Laser Cut",
			CategoryIdx: 2,
			SKUPrefix:   "FASH-W",
			Description: "Jilbab voal ultrafine lembut tidak menerawang, mudah dibentuk tegak di dahi tanpa kusut, dengan finishing tepi laser cut yang rapi.",
			Price:       69000,
			Stock:       90,
			LowStock:    20,
			ImageURL:    "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80",
			Badge:       "BEST SELLER",
			Rating:      4.9,
		},
		{
			Name:        "Tas Selempang Wanita Mini Crossbody Kulit Quilted",
			CategoryIdx: 2,
			SKUPrefix:   "FASH-W",
			Description: "Sling bag wanita motif jahitan quilted elegan dengan tali rantai emas berpadu kulit, muat smartphone, dompet kecil, dan kosmetik esensial.",
			Price:       219000,
			Stock:       28,
			LowStock:    6,
			ImageURL:    "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=600&auto=format&fit=crop&q=80",
			Badge:       "MEWAH",
			Rating:      4.8,
		},
		{
			Name:        "Rok Plisket Pleated Skirt Panjang Maxi Premium",
			CategoryIdx: 2,
			SKUPrefix:   "FASH-W",
			Description: "Rok plisket panjang berbahan hyget super tebal glossy, lipatan rapi tidak mudah pudar walau dicuci, dan ban pinggang elastis nyaman.",
			Price:       119000,
			Stock:       50,
			LowStock:    10,
			ImageURL:    "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&auto=format&fit=crop&q=80",
			Badge:       "FAVORIT",
			Rating:      4.7,
		},
		{
			Name:        "Kemeja Tunik Wanita Katun Rayon Busui Friendly",
			CategoryIdx: 2,
			SKUPrefix:   "FASH-W",
			Description: "Tunik panjang katun rayon twill adem jatuh dengan kancing depan aktif ramah ibu menyusui, pergelangan tangan manset wudhu-friendly.",
			Price:       169000,
			Stock:       32,
			LowStock:    6,
			ImageURL:    "https://images.unsplash.com/photo-1589465885857-44edb59bbff2?w=600&auto=format&fit=crop&q=80",
			Badge:       "MODIS",
			Rating:      4.8,
		},
		{
			Name:        "Piyama Set Wanita Sutra Satin Silk Celana Panjang",
			CategoryIdx: 2,
			SKUPrefix:   "FASH-W",
			Description: "Baju tidur piyama setelan wanita bahan silk satin premium lembut berkilau, sejuk di kulit saat tidur dengan aksen lis kontras elegan.",
			Price:       159000,
			Stock:       45,
			LowStock:    9,
			ImageURL:    "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&auto=format&fit=crop&q=80",
			Badge:       "NYAMAN TIDUR",
			Rating:      4.8,
		},
		{
			Name:        "Sandal Heels Wanita Hak Tahu 5cm Tali Belakang",
			CategoryIdx: 2,
			SKUPrefix:   "FASH-W",
			Description: "Sepatu hak tahu block heels 5cm kokoh anti-goyang dengan bantalan insole busa empuk dan tali slingback karet elastis yang pas di kaki.",
			Price:       219000,
			Stock:       24,
			LowStock:    5,
			ImageURL:    "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&auto=format&fit=crop&q=80",
			Badge:       "KONDANGAN",
			Rating:      4.7,
		},

		// === 4. PERALATAN RUMAH TANGGA (13 Produk) ===
		{
			Name:        "Penggiling Kopi BaristaCraft Conical Burr Presisi",
			CategoryIdx: 3,
			SKUPrefix:   "HOME",
			Description: "Mata pisau kerucut stainless steel 48mm dengan 30 tingkat kehalusan dari espresso hingga french press, motor suara hening, dan ruang anti-statis.",
			Price:       699000,
			Stock:       15,
			LowStock:    5,
			ImageURL:    "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80",
			Badge:       "PILIHAN BARISTA",
			Rating:      4.9,
		},
		{
			Name:        "Lampu Meja Cerdas Dimmable Nordic Glow Ambient",
			CategoryIdx: 3,
			SKUPrefix:   "HOME",
			Description: "Lampu tidur minimalis aluminium dengan kontrol sentuh step-less dimming halus, pengaturan suhu warna cahaya 2700K-6500K, dan tatakan wireless charging 15W.",
			Price:       429000,
			Stock:       28,
			LowStock:    7,
			ImageURL:    "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop&q=80",
			Badge:       "POPULER",
			Rating:      4.7,
		},
		{
			Name:        "Air Fryer Digital Kapasitas 4.5L Layar Sentuh",
			CategoryIdx: 3,
			SKUPrefix:   "HOME",
			Description: "Penggoreng tanpa minyak kapasitas 4.5 Liter dengan sirkulasi udara panas 360 derajat 1400W, 8 program memasak otomatis, dan keranjang anti-lengket bebas PFOA.",
			Price:       589000,
			Stock:       20,
			LowStock:    5,
			ImageURL:    "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80",
			Badge:       "SEHAT",
			Rating:      4.9,
		},
		{
			Name:        "Set Pisau Dapur ChefMaster Stainless Damascus 6-in-1",
			CategoryIdx: 3,
			SKUPrefix:   "HOME",
			Description: "Set pisau dapur baja tahan karat tajam anti-lengket dengan pegangan ergonomis kayu eboni dan blok pisau magnetik modern berbahan akrilik.",
			Price:       359000,
			Stock:       25,
			LowStock:    6,
			ImageURL:    "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=600&auto=format&fit=crop&q=80",
			Badge:       "CHEF CHOICE",
			Rating:      4.8,
		},
		{
			Name:        "Diffuser Aromaterapi Ultrasonik Ultrasonic 500ml Lampu LED",
			CategoryIdx: 3,
			SKUPrefix:   "HOME",
			Description: "Pelembab udara humidifier 500ml dengan teknologi ultrasonik hening, 7 warna lampu ambient relaksasi, timer otomatis, dan remote kontrol jarak jauh.",
			Price:       179000,
			Stock:       50,
			LowStock:    10,
			ImageURL:    "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&auto=format&fit=crop&q=80",
			Badge:       "RELAKSASI",
			Rating:      4.8,
		},
		{
			Name:        "Blender Portable USB Rechargeable 6 Mata Pisau",
			CategoryIdx: 3,
			SKUPrefix:   "HOME",
			Description: "Jus blender mini portabel botol 400ml dengan 6 mata pisau baja 304, baterai lithium 4000mAh kuat menghancurkan es batu dan buah segar di mana saja.",
			Price:       139000,
			Stock:       45,
			LowStock:    9,
			ImageURL:    "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&auto=format&fit=crop&q=80",
			Badge:       "PRAKTIS",
			Rating:      4.7,
		},
		{
			Name:        "Wajan Frypan Granit Anti Lengket 24cm Bebas PFOA",
			CategoryIdx: 3,
			SKUPrefix:   "HOME",
			Description: "Wajan penggorengan lapisan granit Jerman 5 layer anti-lengket, dasar induksi tebal menghantarkan panas merata, dan gagang kayu bakelit tahan panas.",
			Price:       219000,
			Stock:       35,
			LowStock:    7,
			ImageURL:    "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80",
			Badge:       "DAPUR",
			Rating:      4.8,
		},
		{
			Name:        "Timbangan Dapur Digital Presisi 0.1g Layar LCD",
			CategoryIdx: 3,
			SKUPrefix:   "HOME",
			Description: "Timbangan elektronik kue dan kopi dengan akurasi 0.1 gram hingga kapasitas 3kg, fungsi tare wadah, timer seduh kopi, dan permukaan silikon tahan air.",
			Price:       119000,
			Stock:       60,
			LowStock:    12,
			ImageURL:    "https://images.unsplash.com/photo-1584269600519-112d071b35e6?w=600&auto=format&fit=crop&q=80",
			Badge:       "PRESET KOPI",
			Rating:      4.9,
		},
		{
			Name:        "Teko Listrik Kettle Gooseneck Suhu Presisi 800ml",
			CategoryIdx: 3,
			SKUPrefix:   "HOME",
			Description: "Teko leher angsa pour-over kopi stainless steel dengan pengatur suhu digital presisi derajat Celcius, fungsi keep warm 2 jam, dan daya hemat 1000W.",
			Price:       489000,
			Stock:       18,
			LowStock:    4,
			ImageURL:    "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&auto=format&fit=crop&q=80",
			Badge:       "POUR OVER",
			Rating:      4.9,
		},
		{
			Name:        "Vacuum Cleaner Portabel Nirkabel Cordless 12000Pa",
			CategoryIdx: 3,
			SKUPrefix:   "HOME",
			Description: "Penyedot debu genggam ringan tanpa kabel dengan daya hisap kuat 12000Pa, filter HEPA yang bisa dicuci, dan berbagai nozzle untuk mobil dan sofa.",
			Price:       299000,
			Stock:       30,
			LowStock:    6,
			ImageURL:    "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&auto=format&fit=crop&q=80",
			Badge:       "BERSIH KILAT",
			Rating:      4.7,
		},
		{
			Name:        "Sapu Pel Otomatis Spin Mop Microfiber Ember Bilas",
			CategoryIdx: 3,
			SKUPrefix:   "HOME",
			Description: "Set alat pel lantai dengan ember pemeras otomatis tanpa kotori tangan, kepala pel microfiber putar 360 derajat menjangkau kolong perabot.",
			Price:       159000,
			Stock:       40,
			LowStock:    8,
			ImageURL:    "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&auto=format&fit=crop&q=80",
			Badge:       "RUMAH",
			Rating:      4.7,
		},
		{
			Name:        "Kotak Penyimpanan Makanan Kaca Borosilikat Tutup Kedap",
			CategoryIdx: 3,
			SKUPrefix:   "HOME",
			Description: "Wadah bekal makanan kaca tahan panas oven microwave hingga 400C dengan tutup klip silikon kedap udara anti-tumpah 4 sisi.",
			Price:       89000,
			Stock:       70,
			LowStock:    15,
			ImageURL:    "https://images.unsplash.com/photo-1584269600519-112d071b35e6?w=600&auto=format&fit=crop&q=80",
			Badge:       "FOOD GRADE",
			Rating:      4.8,
		},
		{
			Name:        "Rak Piring Dapur Stainless Steel 2 Tingkat Anti Karat",
			CategoryIdx: 3,
			SKUPrefix:   "HOME",
			Description: "Rak pengering piring mangkok dua susun berbahan stainless steel 304 anti karat dilengkapi nampan penampung air tirisan yang bisa ditarik.",
			Price:       239000,
			Stock:       22,
			LowStock:    5,
			ImageURL:    "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80",
			Badge:       "RAPI",
			Rating:      4.8,
		},

		// === 5. OLAHRAGA & OUTDOOR (12 Produk) ===
		{
			Name:        "Tas Ransel Gunung Nomad 35L Waterproof Rolltop",
			CategoryIdx: 4,
			SKUPrefix:   "SPRT",
			Description: "Ransel bahan Cordura 900D anti air dengan kompartemen laptop 16 inci empuk, bantalan punggung sirkulasi udara ergonomis, dan kapasitas fleksibel ekspansi rolltop.",
			Price:       649000,
			Stock:       4,
			LowStock:    5,
			ImageURL:    "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80",
			Badge:       "⚠️ STOK MENIPIS",
			Rating:      5.0,
		},
		{
			Name:        "Tumbler Termos Stainless Vacuum Insulated 1000ml",
			CategoryIdx: 4,
			SKUPrefix:   "SPRT",
			Description: "Botol minum stainless steel food-grade 18/8 penahan dingin hingga 24 jam dan panas hingga 12 jam, lapisan powder coat anti-selip dan tutup magnetik anti-bocor.",
			Price:       249000,
			Stock:       50,
			LowStock:    10,
			ImageURL:    "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80",
			Badge:       "WASPADA DEHIDRASI",
			Rating:      4.8,
		},
		{
			Name:        "Matras Yoga Mat TPE Tebal 8mm Anti-Slip Eco Friendly",
			CategoryIdx: 4,
			SKUPrefix:   "SPRT",
			Description: "Matras senam yoga dan pilates bahan TPE ramah lingkungan dengan garis posisi pemandu tubuh, tekstur anti-selip dua sisi, dan tali jinjing gratis.",
			Price:       189000,
			Stock:       35,
			LowStock:    7,
			ImageURL:    "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&auto=format&fit=crop&q=80",
			Badge:       "YOGA & PILATES",
			Rating:      4.8,
		},
		{
			Name:        "Tali Skipping Jump Rope Bearing Baja Kecepatan Tinggi",
			CategoryIdx: 4,
			SKUPrefix:   "SPRT",
			Description: "Tali lompat cardio kawat baja lapis PVC dengan putaran bearing bola 360 derajat lancar tanpa tersangkut dan gagang aluminium bertekstur anti-keringat.",
			Price:       89000,
			Stock:       65,
			LowStock:    15,
			ImageURL:    "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&auto=format&fit=crop&q=80",
			Badge:       "CARDIO",
			Rating:      4.9,
		},
		{
			Name:        "Tenda Camping Dome Otomatis 4 Orang Waterproof",
			CategoryIdx: 4,
			SKUPrefix:   "SPRT",
			Description: "Tenda kemah hidrolik otomatis buka dalam 3 detik untuk 3-4 orang, bahan polyester 210T tahan hujan 3000mm, dan ventilasi jaring anti-nyamuk.",
			Price:       789000,
			Stock:       12,
			LowStock:    3,
			ImageURL:    "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&auto=format&fit=crop&q=80",
			Badge:       "CAMPING",
			Rating:      4.9,
		},
		{
			Name:        "Set Karet Resistance Band 5 Tingkat Beban Gym",
			CategoryIdx: 4,
			SKUPrefix:   "SPRT",
			Description: "Set karet latihan otot elastis lateks 100% dengan 5 tingkat resistensi beban dari 10 lbs hingga 50 lbs, lengkap dengan pegangan busa dan jangkar pintu.",
			Price:       129000,
			Stock:       55,
			LowStock:    10,
			ImageURL:    "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80",
			Badge:       "HOME WORKOUT",
			Rating:      4.8,
		},
		{
			Name:        "Kursi Lipat Camping Portabel Outdoor Aluminium Ringan",
			CategoryIdx: 4,
			SKUPrefix:   "SPRT",
			Description: "Kursi santai outdoor lipat rangka aluminium aerospace 7075 kuat menahan beban hingga 130kg dengan kain oxford bernapas dan tas simpan ringkas.",
			Price:       179000,
			Stock:       30,
			LowStock:    6,
			ImageURL:    "https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=600&auto=format&fit=crop&q=80",
			Badge:       "OUTDOOR",
			Rating:      4.7,
		},
		{
			Name:        "Celana Legging Olahraga Wanita High Waist Seamless",
			CategoryIdx: 4,
			SKUPrefix:   "SPRT",
			Description: "Legging training elastis tanpa jahitan samping (seamless), kompresi perut nyaman menopang pinggul, bahan cepat kering anti-bakteri.",
			Price:       159000,
			Stock:       40,
			LowStock:    8,
			ImageURL:    "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop&q=80",
			Badge:       "ACTIVEWEAR",
			Rating:      4.8,
		},
		{
			Name:        "Lampu Tenda Kemah Camping LED Solar & USB Rechargeable",
			CategoryIdx: 4,
			SKUPrefix:   "SPRT",
			Description: "Lentera gantung darurat tenaga surya dan USB dengan 5 mode penerangan, fungsi powerbank darurat ponsel, dan gantungan karabiner praktis.",
			Price:       99000,
			Stock:       48,
			LowStock:    10,
			ImageURL:    "https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=600&auto=format&fit=crop&q=80",
			Badge:       "SURVIVAL",
			Rating:      4.7,
		},
		{
			Name:        "Kacamata Renang Anti Fog UV Protection Silikon Lembut",
			CategoryIdx: 4,
			SKUPrefix:   "SPRT",
			Description: "Goggles renang lensa berlapis anti-embun dan anti-UV dengan bingkai segel silikon fleksibel anti-bocor serta penutup telinga terintegrasi.",
			Price:       79000,
			Stock:       60,
			LowStock:    12,
			ImageURL:    "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600&auto=format&fit=crop&q=80",
			Badge:       "RENANG",
			Rating:      4.8,
		},
		{
			Name:        "Tas Sepatu Olahraga Gym Shoe Bag Ventilasi Udara",
			CategoryIdx: 4,
			SKUPrefix:   "SPRT",
			Description: "Pouch tempat sepatu futsal dan fitness berbahan polyester tahan air dengan jaring sirkulasi udara anti-bau dan resleting ganda halus.",
			Price:       49000,
			Stock:       80,
			LowStock:    15,
			ImageURL:    "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80",
			Badge:       "AKSESORIS",
			Rating:      4.7,
		},
		{
			Name:        "Kompor Camping Portabel Mini Windproof Lipat",
			CategoryIdx: 4,
			SKUPrefix:   "SPRT",
			Description: "Kompor gas kaleng outdoor dengan pelindung angin model bunga teratai yang bisa dibuka-tutup, pemantik piezo otomatis, dan api biru merata.",
			Price:       119000,
			Stock:       35,
			LowStock:    7,
			ImageURL:    "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&auto=format&fit=crop&q=80",
			Badge:       "CAMPING GEAR",
			Rating:      4.9,
		},

		// === 6. KECANTIKAN & PERAWATAN (12 Produk) ===
		{
			Name:        "Serum Wajah Hydraglow Niacinamide 10% & Centella 30ml",
			CategoryIdx: 5,
			SKUPrefix:   "BEAU",
			Description: "Serum pencerah kulit wajah dengan konsentrasi Niacinamide 10% dan ekstrak Centella Asiatica alami, efektif menyamarkan noda hitam dan memperkuat skin barrier.",
			Price:       179000,
			Stock:       35,
			LowStock:    8,
			ImageURL:    "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80",
			Badge:       "BEST SELLER",
			Rating:      4.9,
		},
		{
			Name:        "Tabir Surya Sunscreen Gel SPF 50+ PA++++ No Whitecast",
			CategoryIdx: 5,
			SKUPrefix:   "BEAU",
			Description: "Sunscreen tekstur gel seringan air dengan perlindungan maksimal UVA/UVB SPF 50+ PA++++, tidak lengket, bebas alkohol, dan tidak meninggalkan residu putih.",
			Price:       119000,
			Stock:       60,
			LowStock:    12,
			ImageURL:    "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80",
			Badge:       "FAVORIT",
			Rating:      4.9,
		},
		{
			Name:        "Pembersih Wajah Low pH Gentle Cleanser Ceramide 100ml",
			CategoryIdx: 5,
			SKUPrefix:   "BEAU",
			Description: "Sabun cuci muka formula lembut pH seimbang 5.5 dengan kandungan 5X Ceramide dan Asam Amino, membersihkan kotoran pori tanpa membuat kulit kering tertarik.",
			Price:       89000,
			Stock:       50,
			LowStock:    10,
			ImageURL:    "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80",
			Badge:       "KULIT SENSITIF",
			Rating:      4.8,
		},
		{
			Name:        "Moisturizer Gel Hyaluronic Acid & Panthenol 50g",
			CategoryIdx: 5,
			SKUPrefix:   "BEAU",
			Description: "Pelembab wajah tekstur water-gel yang langsung meresap memberi hidrasi instan 72 jam, menenangkan kulit kemerahan, dan mengontrol minyak berlebih.",
			Price:       139000,
			Stock:       45,
			LowStock:    9,
			ImageURL:    "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&auto=format&fit=crop&q=80",
			Badge:       "HIDRASI TINGGI",
			Rating:      4.8,
		},
		{
			Name:        "Toner Eksfoliasi AHA BHA PHA Salicylic Acid 150ml",
			CategoryIdx: 5,
			SKUPrefix:   "BEAU",
			Description: "Toner eksfoliasi harian lembut untuk mengangkat sel kulit mati, membersihkan komedo pori tersumbat, dan menghaluskan tekstur kulit beruntusan.",
			Price:       149000,
			Stock:       38,
			LowStock:    8,
			ImageURL:    "https://images.unsplash.com/photo-1608248597359-0f04c6a6f671?w=600&auto=format&fit=crop&q=80",
			Badge:       "ANTI KOMEDO",
			Rating:      4.7,
		},
		{
			Name:        "Clay Mask Mugwort Pore Clarifying Treatment 55g",
			CategoryIdx: 5,
			SKUPrefix:   "BEAU",
			Description: "Masker bilas ekstrak Mugwort murni untuk menenangkan jerawat meradang, membersihkan minyak pori secara mendalam, dan mencerahkan kulit kusam.",
			Price:       109000,
			Stock:       40,
			LowStock:    8,
			ImageURL:    "https://images.unsplash.com/photo-1567928815117-ac75a968a3e7?w=600&auto=format&fit=crop&q=80",
			Badge:       "MASKER VIRAL",
			Rating:      4.8,
		},
		{
			Name:        "Lip Tint Stain Glossy Berry Longlasting 12 Jam",
			CategoryIdx: 5,
			SKUPrefix:   "BEAU",
			Description: "Pewarna bibir tint bertekstur watery gel ringan dengan pigmentasi intens tahan noda hingga 12 jam, diperkaya Vitamin E dan Jojoba Oil yang melembabkan.",
			Price:       69000,
			Stock:       80,
			LowStock:    15,
			ImageURL:    "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&auto=format&fit=crop&q=80",
			Badge:       "LIP TINT",
			Rating:      4.8,
		},
		{
			Name:        "Minyak Wangi Eau De Parfum Vanilla Sandalwood 50ml",
			CategoryIdx: 5,
			SKUPrefix:   "BEAU",
			Description: "Parfum EDP unisex dengan aroma pembuka vanilla hangat, berpadu wangi kayu cendana mewah dan amber sensual, tahan hingga 8-10 jam.",
			Price:       249000,
			Stock:       25,
			LowStock:    5,
			ImageURL:    "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&auto=format&fit=crop&q=80",
			Badge:       "AROMA MEWAH",
			Rating:      4.9,
		},
		{
			Name:        "Serum Bulu Mata & Alis Peptida Ekstrak Castor Oil",
			CategoryIdx: 5,
			SKUPrefix:   "BEAU",
			Description: "Serum nutrisi pelentik bulu mata dan penebal alis dengan formula peptide aktif alami yang tidak perih di mata dalam pemakaian teratur.",
			Price:       79000,
			Stock:       60,
			LowStock:    12,
			ImageURL:    "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600&auto=format&fit=crop&q=80",
			Badge:       "PELENTIK",
			Rating:      4.7,
		},
		{
			Name:        "Sabun Mandi Aromaterapi Lavender & Chamomile 500ml",
			CategoryIdx: 5,
			SKUPrefix:   "BEAU",
			Description: "Body wash sabun cair relaksasi dengan ekstrak bunga lavender alami busa melimpah, melembabkan kulit tubuh dan menenangkan pikiran sebelum tidur.",
			Price:       89000,
			Stock:       50,
			LowStock:    10,
			ImageURL:    "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80",
			Badge:       "SPA RUMAH",
			Rating:      4.8,
		},
		{
			Name:        "Hair Tonic Ginseng Ekstrak Penumbuh & Anti Rontok 100ml",
			CategoryIdx: 5,
			SKUPrefix:   "BEAU",
			Description: "Tonik perawatan akar rambut dengan ekstrak akar ginseng merah Korea dan biotin murni, menguatkan akar rambut dan mengurangi kerontokan.",
			Price:       119000,
			Stock:       35,
			LowStock:    7,
			ImageURL:    "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=600&auto=format&fit=crop&q=80",
			Badge:       "RAMBUT SEHAT",
			Rating:      4.8,
		},
		{
			Name:        "Kapas Wajah Organik 100% Cotton Tanpa Pemutih 120pcs",
			CategoryIdx: 5,
			SKUPrefix:   "BEAU",
			Description: "Kapas pembersih wajah ultra lembut serat rapat tidak mudah koyak, bebas klorin dan pemutih, hemat cairan toner hingga 50%.",
			Price:       29000,
			Stock:       100,
			LowStock:    20,
			ImageURL:    "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80",
			Badge:       "MURAH",
			Rating:      4.9,
		},

		// === 7. MAKANAN & MINUMAN SEHAT (12 Produk) ===
		{
			Name:        "Biji Kopi Arabika Gayo Single Origin Specialty 250g",
			CategoryIdx: 6,
			SKUPrefix:   "FOOD",
			Description: "Biji kopi sangrai specialty arabika dataran tinggi Gayo Aceh dengan proses semi-washed, profil rasa kompleks dark chocolate, brown sugar, dan aroma floral segar.",
			Price:       115000,
			Stock:       40,
			LowStock:    8,
			ImageURL:    "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&auto=format&fit=crop&q=80",
			Badge:       "SINGLE ORIGIN",
			Rating:      5.0,
		},
		{
			Name:        "Madu Hutan Murni Asli Sumbawa Raw Honey 500g",
			CategoryIdx: 6,
			SKUPrefix:   "FOOD",
			Description: "Madu mentah alami tanpa proses pemanasan atau pemanis buatan dari lebah hutan liar Sumbawa, kaya enzim alami dan antioksidan tinggi untuk daya tahan tubuh.",
			Price:       145000,
			Stock:       30,
			LowStock:    6,
			ImageURL:    "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&auto=format&fit=crop&q=80",
			Badge:       "100% MURNI",
			Rating:      4.9,
		},
		{
			Name:        "Teh Hijau Melati Organik Premium Jasmine Green Tea 100g",
			CategoryIdx: 6,
			SKUPrefix:   "FOOD",
			Description: "Pucuk daun teh hijau pilihan beraroma bunga melati alami perkebunan Jawa Barat, kaya katekin dan epigallocatechin gallate (EGCG) penyegar tubuh.",
			Price:       75000,
			Stock:       50,
			LowStock:    10,
			ImageURL:    "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80",
			Badge:       "AROMA RELAKS",
			Rating:      4.8,
		},
		{
			Name:        "Granola Coklat Mete & Almond Roasted Organik 400g",
			CategoryIdx: 6,
			SKUPrefix:   "FOOD",
			Description: "Sereal sarapan sehat gandum rolled oat panggang dengan potongan kacang mede, almond, biji labu, dan bubuk kakao murni tanpa gula rafinasi.",
			Price:       89000,
			Stock:       45,
			LowStock:    9,
			ImageURL:    "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=600&auto=format&fit=crop&q=80",
			Badge:       "SARAPAN SEHAT",
			Rating:      4.8,
		},
		{
			Name:        "Minyak Kelapa Murni Extra Virgin Coconut Oil (VCO) 500ml",
			CategoryIdx: 6,
			SKUPrefix:   "FOOD",
			Description: "Minyak kelapa murni proses cold-pressed higienis asam laurat tinggi, bisa diminum langsung untuk kesehatan metabolisme atau perawatan rambut alami.",
			Price:       69000,
			Stock:       35,
			LowStock:    7,
			ImageURL:    "https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=600&auto=format&fit=crop&q=80",
			Badge:       "COLD PRESSED",
			Rating:      4.9,
		},
		{
			Name:        "Sambal Bawang Kemasan Kaca Spesial Bawang Goreng 200g",
			CategoryIdx: 6,
			SKUPrefix:   "FOOD",
			Description: "Sambal bawang ulek asli cabai rawit segar dan bawang merah Brebes dengan minyak nabati berkualitas, pedas gurih autentik tanpa pengawet sintetis.",
			Price:       39000,
			Stock:       70,
			LowStock:    15,
			ImageURL:    "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
			Badge:       "PEDAS NIKMAT",
			Rating:      4.9,
		},
		{
			Name:        "Keripik Tempe Renyah Gurih Bumbu Rempah Daun Jeruk 250g",
			CategoryIdx: 6,
			SKUPrefix:   "FOOD",
			Description: "Camilan keripik tempe kedelai non-GMO potongan tipis renyah bertabur daun jeruk purut harum dan rempah bawang gurih.",
			Price:       29000,
			Stock:       80,
			LowStock:    16,
			ImageURL:    "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
			Badge:       "CAMILAN",
			Rating:      4.8,
		},
		{
			Name:        "Cokelat Hitam Dark Chocolate 85% Kakao Asli Bali 100g",
			CategoryIdx: 6,
			SKUPrefix:   "FOOD",
			Description: "Batang cokelat hitam artisanal bean-to-bar dengan 85% biji kakao fermentasi Jembrana Bali, rasa intens sedikit asam buah dan antioksidan tinggi.",
			Price:       55000,
			Stock:       40,
			LowStock:    8,
			ImageURL:    "https://images.unsplash.com/photo-1511381939415-e44015466834?w=600&auto=format&fit=crop&q=80",
			Badge:       "ARTISANAL",
			Rating:      4.9,
		},
		{
			Name:        "Chia Seeds Organik Superfood Mexico 250g",
			CategoryIdx: 6,
			SKUPrefix:   "FOOD",
			Description: "Biji chia organik grade premium tinggi serat larut, asam lemak Omega-3 nabati, dan protein untuk campuran smoothie, puding, atau oatmeal.",
			Price:       49000,
			Stock:       50,
			LowStock:    10,
			ImageURL:    "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=600&auto=format&fit=crop&q=80",
			Badge:       "SUPERFOOD",
			Rating:      4.8,
		},
		{
			Name:        "Kopi Bubuk Robusta Dampit Malang Full Body 250g",
			CategoryIdx: 6,
			SKUPrefix:   "FOOD",
			Description: "Kopi robusta Dampit Jawa Timur profil dark roast tebal dengan crema melimpah, aroma kacang karamel, dan kadar kafein mantap penambah fokus.",
			Price:       45000,
			Stock:       60,
			LowStock:    12,
			ImageURL:    "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&auto=format&fit=crop&q=80",
			Badge:       "MANTAP",
			Rating:      4.8,
		},
		{
			Name:        "Garam Laut Himalaya Pink Salt Halus Murni 500g",
			CategoryIdx: 6,
			SKUPrefix:   "FOOD",
			Description: "Garam kristal merah muda alami pegunungan Himalaya mengandung 84 mineral mikro alami tanpa zat pemutih atau anti-gumpal.",
			Price:       35000,
			Stock:       75,
			LowStock:    15,
			ImageURL:    "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&auto=format&fit=crop&q=80",
			Badge:       "MINERAL",
			Rating:      4.9,
		},
		{
			Name:        "Minuman Jahe Merah Instan Gula Aren Alami 200g",
			CategoryIdx: 6,
			SKUPrefix:   "FOOD",
			Description: "Bubuk seduh jahe merah hangat berpadu gula aren asli dan rempah sereh cengkeh alami untuk menghangatkan badan dan meredakan masuk angin.",
			Price:       39000,
			Stock:       65,
			LowStock:    12,
			ImageURL:    "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80",
			Badge:       "HERBAL",
			Rating:      4.8,
		},

		// === 8. BUKU & ALAT TULIS (11 Produk) ===
		{
			Name:        "Buku Catatan Jurnal Kulit Leather Notebook A5 Dotted",
			CategoryIdx: 7,
			SKUPrefix:   "STAT",
			Description: "Buku jurnal cover kulit PU tebal isi 192 halaman kertas gading 100 gsm titik (dotted) anti tembus tinta fountain pen, pita pembatas, dan kantong belakang.",
			Price:       119000,
			Stock:       35,
			LowStock:    7,
			ImageURL:    "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
			Badge:       "JOURNALING",
			Rating:      4.9,
		},
		{
			Name:        "Set Pulpen Gel Tinta Hitam 0.5mm Cepat Kering 6pcs",
			CategoryIdx: 7,
			SKUPrefix:   "STAT",
			Description: "Set pulpen pena gel bodi matte ergonomis tinta pigmen jepang 0.5mm hitam pekat anti blobor, cepat kering, dan sangat lancar untuk menulis catatan.",
			Price:       49000,
			Stock:       90,
			LowStock:    20,
			ImageURL:    "https://images.unsplash.com/photo-1585336261026-7f576e2820d8?w=600&auto=format&fit=crop&q=80",
			Badge:       "TULIS LANCAR",
			Rating:      4.8,
		},
		{
			Name:        "Planner Harian Undated Daily Planner Agenda Produktif",
			CategoryIdx: 7,
			SKUPrefix:   "STAT",
			Description: "Buku agenda perencana target harian tanpa tanggal (undated) dengan matriks prioritas tugas, tracker minum air, jadwal jam, dan refleksi harian.",
			Price:       139000,
			Stock:       30,
			LowStock:    6,
			ImageURL:    "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=600&auto=format&fit=crop&q=80",
			Badge:       "PRODUKTIF",
			Rating:      4.9,
		},
		{
			Name:        "Lampu Baca Buku Jepit LED Fleksibel 3 Mode Warna",
			CategoryIdx: 7,
			SKUPrefix:   "STAT",
			Description: "Lampu baca klip leher fleksibel 360 derajat baterai isi ulang USB dengan 3 pilihan suhu cahaya ramah mata untuk membaca malam hari tanpa silau.",
			Price:       79000,
			Stock:       45,
			LowStock:    9,
			ImageURL:    "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop&q=80",
			Badge:       "BACA NYAMAN",
			Rating:      4.7,
		},
		{
			Name:        "Tempat Pensil Organizer Meja Kayu Jati Minimalis",
			CategoryIdx: 7,
			SKUPrefix:   "STAT",
			Description: "Tempat alat tulis meja kerja berbahan kayu jati solid natural dengan 4 sekat penyimpanan pulpen, penggaris, gunting, dan slot sandaran handphone.",
			Price:       99000,
			Stock:       25,
			LowStock:    5,
			ImageURL:    "https://images.unsplash.com/photo-1585336261026-7f576e2820d8?w=600&auto=format&fit=crop&q=80",
			Badge:       "KAYU JATI",
			Rating:      4.8,
		},
		{
			Name:        "Set Spidol Highlighter Pastel Anti Tembus 6 Warna",
			CategoryIdx: 7,
			SKUPrefix:   "STAT",
			Description: "Spidol penanda buku teks 6 warna pastel lembut di mata dengan ujung ganda chisel tip untuk garis tebal dan tipis tanpa merusak kertas.",
			Price:       39000,
			Stock:       75,
			LowStock:    15,
			ImageURL:    "https://images.unsplash.com/photo-1585336261026-7f576e2820d8?w=600&auto=format&fit=crop&q=80",
			Badge:       "PASTEL",
			Rating:      4.8,
		},
		{
			Name:        "Tas Dokumen Laptop Organizer A4 Waterproof Briefcase",
			CategoryIdx: 7,
			SKUPrefix:   "STAT",
			Description: "Folder tas arsip dokumen berkas A4 bahan oxford anti-air dengan 8 kompartemen saku dalam resleting untuk membawa laptop 13 inci dan paspor.",
			Price:       129000,
			Stock:       35,
			LowStock:    7,
			ImageURL:    "https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80",
			Badge:       "KANTOR",
			Rating:      4.8,
		},
		{
			Name:        "Buku Catatan Sketsa Sketchbook Kertas Tebal 160gsm A4",
			CategoryIdx: 7,
			SKUPrefix:   "STAT",
			Description: "Buku gambar sketsa jilid spiral kawat isi 60 lembar kertas tebal 160 gsm bebas asam, cocok untuk pensil grafit, arang, cat air, dan spidol marker.",
			Price:       89000,
			Stock:       40,
			LowStock:    8,
			ImageURL:    "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
			Badge:       "SKETCH",
			Rating:      4.9,
		},
		{
			Name:        "Sticky Notes Memo Tempel Morandi Pastel Transparan",
			CategoryIdx: 7,
			SKUPrefix:   "STAT",
			Description: "Kertas memo tempel plastik PET transparan tahan air warna Morandi aesthetic yang bisa ditulisi pulpen tanpa menutupi teks buku di bawahnya.",
			Price:       25000,
			Stock:       120,
			LowStock:    25,
			ImageURL:    "https://images.unsplash.com/photo-1585336261026-7f576e2820d8?w=600&auto=format&fit=crop&q=80",
			Badge:       "AESTHETIC",
			Rating:      4.8,
		},
		{
			Name:        "Gunting Kertas Stainless Lapisan Titanium Anti-Lengket",
			CategoryIdx: 7,
			SKUPrefix:   "STAT",
			Description: "Gunting kantor presisi mata pisau baja lapis titanium anti-lengket sisa lem isolasi dengan pegangan karet lembut ergonomis.",
			Price:       35000,
			Stock:       60,
			LowStock:    12,
			ImageURL:    "https://images.unsplash.com/photo-1585336261026-7f576e2820d8?w=600&auto=format&fit=crop&q=80",
			Badge:       "TAJAM",
			Rating:      4.8,
		},
		{
			Name:        "Stapler Tembak Paper Binder Tanpa Jarum Klip Kertas",
			CategoryIdx: 7,
			SKUPrefix:   "STAT",
			Description: "Alat klip kertas dorong clamshell modern yang bisa menjepit hingga 40 lembar kertas tanpa melubangi dan klipnya dapat digunakan berulang kali.",
			Price:       45000,
			Stock:       50,
			LowStock:    10,
			ImageURL:    "https://images.unsplash.com/photo-1585336261026-7f576e2820d8?w=600&auto=format&fit=crop&q=80",
			Badge:       "PRAKTIS",
			Rating:      4.7,
		},
	}

	// Buat 100 Produk dengan SKU dan Slug yang Unik & Bersih
	productsToInsert := make([]product.Product, 0, len(catalog))
	for idx, item := range catalog {
		sku := fmt.Sprintf("%s-%03d", item.SKUPrefix, idx+1)
		slug := strings.ToLower(item.Name)
		slug = strings.ReplaceAll(slug, " & ", "-")
		slug = strings.ReplaceAll(slug, "%", "")
		slug = strings.ReplaceAll(slug, "+", "")
		slug = strings.ReplaceAll(slug, "/", "-")
		slug = strings.ReplaceAll(slug, "(", "")
		slug = strings.ReplaceAll(slug, ")", "")
		slug = strings.ReplaceAll(slug, ".", "-")
		slug = strings.ReplaceAll(slug, ",", "")
		slug = strings.ReplaceAll(slug, " ", "-")
		slug = strings.ReplaceAll(slug, "--", "-")
		slug = fmt.Sprintf("%s-%03d", slug, idx+1)

		p := product.Product{
			CategoryID:        categories[item.CategoryIdx].ID,
			Name:              item.Name,
			Slug:              slug,
			SKU:               sku,
			Description:       item.Description,
			Price:             item.Price,
			StockQuantity:     item.Stock,
			LowStockThreshold: item.LowStock,
			ImageURL:          item.ImageURL,
			IsActive:          true,
			Badge:             item.Badge,
			Rating:            item.Rating,
		}
		db.Create(&p)
		productsToInsert = append(productsToInsert, p)
	}

	// 4. Seed Sample Orders
	if len(productsToInsert) >= 4 {
		order1 := order.Order{
			OrderNumber:     "TC-20260825-102938",
			UserID:          shopper.ID,
			TotalAmount:     productsToInsert[0].Price + productsToInsert[1].Price,
			Status:          order.StatusShipped,
			ShippingName:    "Budi Santoso",
			ShippingPhone:   "+62 812-3456-7890",
			ShippingAddress: "Jl. Menteng Raya No. 24, Jakarta Pusat",
			PaymentMethod:   "BANK_TRANSFER",
			PaymentStatus:   order.PaymentSuccess,
			Notes:           "Mohon titipkan ke pos satpam jika tidak ada orang di rumah",
			CreatedAt:       time.Now().AddDate(0, 0, -2),
		}
		db.Create(&order1)

		db.Create(&order.OrderItem{
			OrderID:      order1.ID,
			ProductID:    productsToInsert[0].ID,
			ProductName:  productsToInsert[0].Name,
			ProductSKU:   productsToInsert[0].SKU,
			ProductImage: productsToInsert[0].ImageURL,
			Quantity:     1,
			UnitPrice:    productsToInsert[0].Price,
			Subtotal:     productsToInsert[0].Price,
		})

		db.Create(&order.OrderItem{
			OrderID:      order1.ID,
			ProductID:    productsToInsert[1].ID,
			ProductName:  productsToInsert[1].Name,
			ProductSKU:   productsToInsert[1].SKU,
			ProductImage: productsToInsert[1].ImageURL,
			Quantity:     1,
			UnitPrice:    productsToInsert[1].Price,
			Subtotal:     productsToInsert[1].Price,
		})

		order2 := order.Order{
			OrderNumber:     "TC-20260826-591823",
			UserID:          sarah.ID,
			TotalAmount:     productsToInsert[3].Price * 2,
			Status:          order.StatusPaid,
			ShippingName:    "Siti Rahmawati",
			ShippingPhone:   "+62 813-7890-1234",
			ShippingAddress: "Jl. Dago Asri No. 12, Bandung, Jawa Barat",
			PaymentMethod:   "CARD",
			PaymentStatus:   order.PaymentSuccess,
			Notes:           "Kirim pada jam kerja (09:00 - 17:00 WIB)",
			CreatedAt:       time.Now().AddDate(0, 0, -1),
		}
		db.Create(&order2)

		db.Create(&order.OrderItem{
			OrderID:      order2.ID,
			ProductID:    productsToInsert[3].ID,
			ProductName:  productsToInsert[3].Name,
			ProductSKU:   productsToInsert[3].SKU,
			ProductImage: productsToInsert[3].ImageURL,
			Quantity:     2,
			UnitPrice:    productsToInsert[3].Price,
			Subtotal:     productsToInsert[3].Price * 2,
		})
	}

	log.Printf("Seeding 100 produk retail bahasa Indonesia berhasil diselesaikan! Total: %d produk 🚀\n", len(productsToInsert))
	_ = rand.Intn
	return nil
}
